name: Terraform Workspaces Setup

on:
  push:
    branches:
      - main  # or any other branch you want to trigger for deploying

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    # Step 3: Authenticate to GCP
    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Select the dev workspace and run Terraform commands
    - name: Select Terraform Workspace (dev)
      run: |
        terraform workspace select dev || terraform workspace new dev
        terraform init
        terraform apply -auto-approve -var-file=./dev/terraform.tfvars

  terraform-stage:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    # Step 3: Authenticate to GCP
    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Select the stage workspace and run Terraform commands
    - name: Select Terraform Workspace (stage)
      run: |
        terraform workspace select stage || terraform workspace new stage
        terraform init
        terraform apply -auto-approve -var-file=./stage/terraform.tfvars

 
