name: Terraform Workspaces Setup

on:
  push:
    branches:
      - main  # or any other branch you want to trigger for deploying

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Select Terraform Workspace (dev)
      run: |
        terraform workspace select dev || terraform workspace new dev
        terraform init -backend-config=./dev/backend-dev.tf  # Specify the backend config for dev

    - name: Terraform Plan (dev)
      working-directory: ./dev  # Change working directory to the dev folder
      run: |
        terraform plan -var-file=./dev/terraform.tfvars

    - name: Terraform Apply (dev)
      working-directory: ./dev  # Change working directory to the dev folder
      run: |
        terraform apply -auto-approve -var-file=./dev/terraform.tfvars

  terraform-stage:
    runs-on: ubuntu-latest
    needs: terraform-dev  # This makes terraform-stage depend on terraform-dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Select Terraform Workspace (stage)
      run: |
        terraform workspace select stage || terraform workspace new stage
        terraform init -backend-config=./stage/backend-stage.tf  # Specify the backend config for stage

    - name: Terraform Plan (stage)
      working-directory: ./stage  # Change working directory to the stage folder
      run: |
        terraform plan -var-file=./stage/terraform.tfvars

    - name: Terraform Apply (stage)
      working-directory: ./stage  # Change working directory to the stage folder
      run: |
        terraform apply -auto-approve -var-file=./stage/terraform.tfvars
