name: Terraform Workspaces Setup

on:
  push:
    branches:
      - main

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    - name: Authenticate to GCP
      working-directory: ./dev
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform init (dev)
      working-directory: ./dev
      run: |
        terraform init

    - name: Select Terraform Workspace (dev)
      working-directory: ./dev  
      run: |
        terraform workspace select dev || terraform workspace new dev

    - name: Terraform Plan (dev)
      working-directory: ./dev
      run: |
        terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply (dev)
      working-directory: ./dev
      run: |
        terraform apply -auto-approve -var-file=terraform.tfvars

  terraform-stage:
    runs-on: ubuntu-latest
    needs: terraform-dev  # Ensure the stage job runs after dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.7'

    - name: Authenticate to GCP
      working-directory: ./stage
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform init (stage)
      working-directory: ./stage
      run: |
        terraform init

    - name: Select Terraform Workspace (stage)
      working-directory: ./stage
      run: |
        terraform workspace select stage || terraform workspace new stage

    - name: Terraform Plan (stage)
      working-directory: ./stage
      run: |
        terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply (stage)
      working-directory: ./stage
      run: |
        terraform apply -auto-approve -var-file=terraform.tfvars
